### ISSUE TITLE
suggestions of two exceptions

### ISSUE THREAD

**Issue by eribul** [MangoTheCat/goodpractice#11]
Thank you very much for a nice package!

I just tried it and had some really useful suggestions that I will absolutely follow.

Two suggestions though:

```
not use "Depends" in DESCRIPTION, as it can cause name clashes, and poor interaction with
    other packages. Use "Imports" instead.
```
I always do this for packages but I do have:
`Depends: R (>= 2.10)`, hence not for a package but for R itself. Mayby the check could apply only to packages and not to the R version?

```
avoid the library() and require() functions, they change the global search path. If you
    need to use other packages, import them. If you need to load them explicitly, then consider
    loadNamespace() instead, or as a last resort, declare them as 'Depends' dependencies.

    tests/testthat.R:1:1
    tests/testthat.R:2:1
```

I newer use `library` myself but the instances above are added by the `devtools` package and I suppose this is very common. Mayby there could be exceptions for this type of use?

**Comment by gaborcsardi** [comment]
Thanks, you are absolutely right about both!

`Depends: R` is fixed in 34a8c2890e8aa192d46b81d65b5c9e4aeea3ab58

`library()` in test code is fixed in cae5198f942621d43cf81b3c0183f6b0fad25323
