### ISSUE TITLE
Usage example in README.md

### ISSUE THREAD

**Issue by jsta** [MangoTheCat/goodpractice#12]
I am getting path errors if I run the usage example from README.md as:
`gp("mypackage")`

If I run within the "mypackage" folder I get:

> Error in if (is_dir(file)) file <- file.path(file, "DESCRIPTION") : 
  missing value where TRUE/FALSE needed

If I run within the parent of "mypackage" I get:

> Preparing: covr
Error in .rs.normalizePath(marker$file, mustWork = TRUE) : 
  path[1]="R/foobar.R": No such file or directory 

However, I could get it working by moving within the "mypackage" folder and running:

`gp("../mypackage")`

**Comment by gaborcsardi** [comment]
Here is what I get for a simple package of mine. The package is in the `rematch` directory:

```r
❯ library(goodpractice)
❯ x <- gp("rematch")
Preparing: covr
Preparing: cyclocomp
* installing *source* package ‘rematch’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rematch)
Preparing: description
Preparing: lintr
Preparing: namespace
Preparing: rcmdcheck
```

Which is fine. From within the package:

```r
❯ setwd("rematch")
❯ x <- gp(".")
Preparing: covr
Preparing: cyclocomp
* installing *source* package ‘rematch’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rematch)
Preparing: description
Preparing: lintr
Preparing: namespace
Preparing: rcmdcheck
```

which is fine again. Can you please provide a complete, reproducible example? Thanks.

**Comment by jsta** [comment]
Hmm, now I am having trouble reproducing the errors. 

I made several changes to my package based on the `goodpractice` recommendations. Maybe that fixed it.

I apologize if I caused you any trouble.

**Comment by gaborcsardi** [comment]
No worries!
