### ISSUE TITLE
Feature request: check for local temporary files being created

### ISSUE THREAD

**Issue by richelbilderbeek** [MangoTheCat/goodpractice#123]
I am a big fan of `goodpractice` and would like to suggest a new feature:

**Checking if there are local temporary files being created**

 Reason for this feature request is that the `--as-cran` tests do not detect this yet, but the human volunteers do. It would save those humans some time if `goodpractice` would let the devs know beforehand.

I'd be happy to volunteer to test this functionality if needed.

**Comment by gaborcsardi** [comment]
I think recent R-devel checks for this, so goodpractice will pick it up on a recent R version.

**Comment by richelbilderbeek** [comment]
That's great! Sorry for the noise then, will close the Issue.
