### ISSUE TITLE
New check: use inherits() not `class() ==` or `class() %in%`

### ISSUE THREAD

**Issue by bfgray3** [MangoTheCat/goodpractice#125]
Do you think this would be a useful addition?  I'd be happy to implement it in a pull request.

**Comment by gaborcsardi** [comment]
I think it is useful, but not very easy to implement. Were you thinking about the implementation?

**Comment by bfgray3** [comment]
I haven't considered the implementation yet.  I'll close this issue for now.

**Comment by Bisaloo** [comment]
Relevant blog post by the way: https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html
