### ISSUE TITLE
How to handle URLs longer than 80 characters

### ISSUE THREAD

**Issue by florianm** [MangoTheCat/goodpractice#137]
I'm getting warnings from goodpractice about line lengths where I'm embedding long URLs, e.g. 

```
#' @seealso \url{https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/metadata-document}
```

I'd like to avoid using URL shorteners. What's the best practice to pass goodpractice checks for those long lines? I do want to receive warnings about other lines > 80 chars.

**Comment by gaborcsardi** [comment]
I think you can do this:
```r
# nolint start
#' @seealso \url{https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/metadata-document}
# nolint end
```

**Comment by florianm** [comment]
@gaborcsardi thanks heaps, that worked!
