### ISSUE TITLE
Displayment in Markers window

### ISSUE THREAD

**Issue by eribul** [MangoTheCat/goodpractice#16]
Not sure if this is a bug or intended but if I run `gp()` in RStudio and don't have full code coverage, this is displayed nicely in a "Markers" window close to my console.
If I do have 100 % coverage, there is an empty "Markers" window showing up (without any explanaition, which was confusing the first time I saw it).
If I instead run `gp()$linter`, I have the same window but now also with a "lintr" tab and I can toggle between the two.

It´s just so much nicer to have the result of `gp()$lintr` than just `gp()` that I started to wonder if this wasn't in fact the intended behavior?

**Comment by gaborcsardi** [comment]
Interesting. I didn't know about these, I guess some side effect from `lintr`, maybe. Will experiment, thanks for letting me know.
