### ISSUE TITLE
Importing whole packages is sometimes easier

### ISSUE THREAD

**Issue by NattyE** [MangoTheCat/goodpractice#17]
I am wondering if there should be an identifier for where in the code whole packages are being imported. For example in one of my packages I am using `ggplot2` and rather than `@importFrom` every function I am using, I just `@import` the whole package. Obviously in this case it is simple to dismiss the following message:

    ✖ not import packages as a whole, as this can cause name clashes between the imported packages. Instead, import only the
    specific functions you need.

But if you have other packages that are being imported on the whole (accidentally or not), it would be nice if the output pointed to them so you can make the decision whether you should change the code or not a little easier.

**Comment by gaborcsardi** [comment]
The title is somewhat different from the main text, so I am not sure which one you want. Both?

For now you can just ignore the message if you don't like the advice. We'll have some kind of ignore mechanism later.

As for finding the place of the `@import`, yeah, that's somewhat harder. We can't assume Roxygen, so maybe there is no `@import` at all. But this case is easy, it is in `NAMESPACE` then. For the Roxygen case we would need to depend on Roxygen, or have a Roxygen parser.

I am not sure if it is worth the effort, though. In every decent editor, RStudio included, you can search all files in a project (=R package), so finding it takes 2 seconds, literally.

**Comment by gaborcsardi** [comment]
Closing this now, not sure what exactly it was about.
