### ISSUE TITLE
Error in data.frame(stringsAsFactors = FALSE, type = type, package = vapply(deps,  : 

### ISSUE THREAD

**Issue by mdozmorov** [MangoTheCat/goodpractice#40]
Full error message:
Preparing: description
Preparing: lintr
Preparing: namespace
Preparing: rcmdcheck
Error in data.frame(stringsAsFactors = FALSE, type = type, package = vapply(deps,  : 
  arguments imply differing number of rows: 1, 0

Tested on https://github.com/ERGlass/lrcde.dev. Looks like GP breaks on something, can't find out why. The "Build&Reload" in RStudion works fine.

**Comment by gaborcsardi** [comment]
Yep, I can reproduce this.

**Comment by gaborcsardi** [comment]
It is a bug in the `desc` package, it fails on the empty `Depends` field: https://github.com/ERGlass/lrcde.dev/blob/b5fe40580b6435969d81bbfed6163ac15bba866b/DESCRIPTION#L14

**Comment by gaborcsardi** [comment]
It will be fixed in the `desc` package.

**Comment by gaborcsardi** [comment]
Fixed in the dev version of the `desc` package: c020d3dbfd8863d203a2dbc817d7091ec920e989
