### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vdicolab** [MangoTheCat/goodpractice#51]
Dear Gabor,
I would like to use your goodpractice package to test mine, but I get this error in mac:
Error in edges$from[num_edges + (1:n)] <<- head(args, -1) : 
  replacement has length zero
any idea what it is?
Also, I wanted to run it in windows and I could not.
I get: Error in file (con, "r") : cannot open conection

> x<-gp("ecospat")
Preparing: covr
Preparing: cyclocomp
Skipping 2 packages ahead of CRAN: biomod2, gbm
Installing 1 packages: slam

  There is a binary version available (and will be installed) but the
  source version is later:
     binary source
slam 0.1-37 0.1-38

* installing *source* package ‘ecospat’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ecospat)
Error in edges$from[num_edges + (1:n)] <<- head(args, -1) : 
  replacement has length zero

**Comment by gaborcsardi** [comment]
Yes, I can reproduce this.

**Comment by gaborcsardi** [comment]
It is a cyclocomp bug, using `next` without a loop is surprising.... anyway, goodpractice should handle this better.

**Comment by gaborcsardi** [comment]
https://github.com/MangoTheCat/cyclocomp/issues/15
