### ISSUE TITLE
rename main function to goodpractice

### ISSUE THREAD

**Issue by LiNk-NY** [MangoTheCat/goodpractice#52]
Hi @gaborcsardi, 
I can implement this if you'd like but I think the main function in the package should be named `goodpractice`, same as the package. 
What do you think? 
Thanks,
Marcel

**Comment by gaborcsardi** [comment]
Why? I like `gp`. Maybe rename the package to `gp`, rather? :)

But realistically, this won't happen. We are already using this package in internal projects, and it would be painful to rename it everywhere.

**Comment by LiNk-NY** [comment]
Because it's good practice :smile:

**Comment by gaborcsardi** [comment]
I suppose we can make `goodpractice` be an alias to `gp`, and use `goodpractice` in the examples? How about that?

**Comment by LiNk-NY** [comment]
That would work. You don't have to but it would keep things in the spirit of the package. 
Thanks for your contribution! :+1:

**Comment by gaborcsardi** [comment]
Wait, you said you would implement it. :) So do you want to submit a PR?

**Comment by LiNk-NY** [comment]
Yeah, I'll have a look at it. Thanks.

**Comment by LiNk-NY** [comment]
Please see PR #54. 

I'm not sure why appveyor is failing.
