### ISSUE TITLE
guidance option

### ISSUE THREAD

**Issue by maelle** [MangoTheCat/goodpractice#67]
Add an option guidance that'd output messages for the different checks, e.g. for `lintr` issue a mention of `styler`, and for some other checks a mention of the corresponding `usethis` functions.

**Comment by hfrick** [comment]
When you make a check via `make_check()` you need to give it a `gp` argument which contains the advice used by the print method:

```
simple_truefalse_not_tf <- goodpractice::make_check(
  description = "TRUE and FALSE is used, not T and F",
  gp = "avoid 'T' and 'F', use 'TRUE' and 'FALSE' instead.",
  check = function(state) {
      length(tools::checkTnF(dir = state$path)) == 0
  }
)
x <- goodpractice::gp(system.file("bad1", package = "goodpractice"), checks = "simple_tf",
                     extra_checks = list(simple_tf = simple_truefalse_not_tf))
x
```
```
R> x
── GP badpackage ────────────────────────────────────────────────────────────────

It is good practice to

  ✖ avoid 'T' and 'F', use 'TRUE' and 'FALSE' instead.
───────────────────────────────────────────────────────────────────────────────── 
```
You could put any specific guidance in that `gp` argument. Is that sorta what you had in mind or did you want to explicitly separate guidance and "hey, this thing you're doing isn't exactly good practice"?

**Comment by maelle** [comment]
Oh then this issue was useless sorry! Yes that `gp` argument is enough!
