### ISSUE TITLE
How to activate advice?

### ISSUE THREAD

**Issue by peterhurford** [MangoTheCat/goodpractice#7]
The only way I found was `goodpractice:::gp()`, but I don't know why that function wouldn't be exported?

`library(goodpractice)` does nothing and I couldn't find any `onLoad` hooks in this package that would make it work.

**Comment by gaborcsardi** [comment]
Hi! This is very much work in progress. `gp()` will be eventually exported. I do the development in `devtools`, and then it does not matter if it is not exported.

I'll export it in a sec, but again, this package is not very useful currently, and most things, including `gp()` will change.

**Comment by gaborcsardi** [comment]
Exported `gp` in 5d377d299ead9adda9aa84541828f87dc97b1e00

**Comment by peterhurford** [comment]
:+1:
